// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

package com.alibaba.dubbo.performance.demo.agent.proto;

public final class Response {
  private Response() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SearchResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SearchResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 responseId = 1;</code>
     */
    long getResponseId();

    /**
     * <code>int32 hash = 2;</code>
     */
    int getHash();
  }
  /**
   * Protobuf type {@code SearchResponse}
   */
  public  static final class SearchResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SearchResponse)
      SearchResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SearchResponse.newBuilder() to construct.
    private SearchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchResponse() {
      responseId_ = 0L;
      hash_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              responseId_ = input.readInt64();
              break;
            }
            case 16: {

              hash_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.dubbo.performance.demo.agent.proto.Response.internal_static_SearchResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.dubbo.performance.demo.agent.proto.Response.internal_static_SearchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse.class, com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse.Builder.class);
    }

    public static final int RESPONSEID_FIELD_NUMBER = 1;
    private long responseId_;
    /**
     * <code>int64 responseId = 1;</code>
     */
    public long getResponseId() {
      return responseId_;
    }

    public static final int HASH_FIELD_NUMBER = 2;
    private int hash_;
    /**
     * <code>int32 hash = 2;</code>
     */
    public int getHash() {
      return hash_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (responseId_ != 0L) {
        output.writeInt64(1, responseId_);
      }
      if (hash_ != 0) {
        output.writeInt32(2, hash_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (responseId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, responseId_);
      }
      if (hash_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, hash_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse)) {
        return super.equals(obj);
      }
      com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse other = (com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse) obj;

      boolean result = true;
      result = result && (getResponseId()
          == other.getResponseId());
      result = result && (getHash()
          == other.getHash());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getResponseId());
      hash = (37 * hash) + HASH_FIELD_NUMBER;
      hash = (53 * hash) + getHash();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SearchResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SearchResponse)
        com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.dubbo.performance.demo.agent.proto.Response.internal_static_SearchResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.dubbo.performance.demo.agent.proto.Response.internal_static_SearchResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse.class, com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse.Builder.class);
      }

      // Construct using com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        responseId_ = 0L;

        hash_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.dubbo.performance.demo.agent.proto.Response.internal_static_SearchResponse_descriptor;
      }

      public com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse getDefaultInstanceForType() {
        return com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse.getDefaultInstance();
      }

      public com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse build() {
        com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse buildPartial() {
        com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse result = new com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse(this);
        result.responseId_ = responseId_;
        result.hash_ = hash_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse) {
          return mergeFrom((com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse other) {
        if (other == com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse.getDefaultInstance()) return this;
        if (other.getResponseId() != 0L) {
          setResponseId(other.getResponseId());
        }
        if (other.getHash() != 0) {
          setHash(other.getHash());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long responseId_ ;
      /**
       * <code>int64 responseId = 1;</code>
       */
      public long getResponseId() {
        return responseId_;
      }
      /**
       * <code>int64 responseId = 1;</code>
       */
      public Builder setResponseId(long value) {
        
        responseId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 responseId = 1;</code>
       */
      public Builder clearResponseId() {
        
        responseId_ = 0L;
        onChanged();
        return this;
      }

      private int hash_ ;
      /**
       * <code>int32 hash = 2;</code>
       */
      public int getHash() {
        return hash_;
      }
      /**
       * <code>int32 hash = 2;</code>
       */
      public Builder setHash(int value) {
        
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 hash = 2;</code>
       */
      public Builder clearHash() {
        
        hash_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SearchResponse)
    }

    // @@protoc_insertion_point(class_scope:SearchResponse)
    private static final com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse();
    }

    public static com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchResponse>
        PARSER = new com.google.protobuf.AbstractParser<SearchResponse>() {
      public SearchResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchResponse> getParserForType() {
      return PARSER;
    }

    public com.alibaba.dubbo.performance.demo.agent.proto.Response.SearchResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016response.proto\"2\n\016SearchResponse\022\022\n\nre" +
      "sponseId\030\001 \001(\003\022\014\n\004hash\030\002 \001(\005B:\n.com.alib" +
      "aba.dubbo.performance.demo.agent.protoB\010" +
      "Responseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchResponse_descriptor,
        new java.lang.String[] { "ResponseId", "Hash", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
